export * from "./lib/core.service";
export * from "./lib/core.component";
export * from "./lib/core.module";
export * from "./lib/models/lesson";
export * from "./lib/models/resource";
export * from "./lib/models/talk";
export * from "./lib/models/result";
export * from "./lib/components/talks/talks-page/talks-page.component";
export * from "./lib/components/talks/talk-item/talk-item.component";
export * from "./lib/components/talks/talk-items-line/talk-items-line.component";
// export * from "./lib/pipes/sort/sort.pipe";
